#!/bin/sh
cat << EOF
Hello there, my friend!

NEVER GONNA GIVE YOU UP,
NEVER GONNA LET YOU DOWN,
NEVER GONNA RUN AROUND AND DESERT YOU...
NEVER GONNA MAKE YOU CRY,
NEVER GONNA SAY GOODBYE,
NEVER GONNA TELL A LIE AND HURT YOU...

EOF
